#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : distro
Version  : 1.3.0
Release  : 8
URL      : https://github.com/nir0s/distro/archive/v1.3.0.tar.gz
Source0  : https://github.com/nir0s/distro/archive/v1.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: distro-bin
Requires: distro-python3
Requires: distro-license
Requires: distro-python
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv
Patch1: os-release.patch

%description
Distro - an OS platform information API
=======================================
See `Official GitHub repo <https://github.com/nir0s/distro#distro---a-linux-os-platform-information-api>`_.

%package bin
Summary: bin components for the distro package.
Group: Binaries
Requires: distro-license

%description bin
bin components for the distro package.


%package license
Summary: license components for the distro package.
Group: Default

%description license
license components for the distro package.


%package python
Summary: python components for the distro package.
Group: Default
Requires: distro-python3

%description python
python components for the distro package.


%package python3
Summary: python3 components for the distro package.
Group: Default
Requires: python3-core

%description python3
python3 components for the distro package.


%prep
%setup -q -n distro-1.3.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534208467
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/distro
cp LICENSE %{buildroot}/usr/share/doc/distro/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/distro

%files license
%defattr(-,root,root,-)
/usr/share/doc/distro/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
